export const actionTypes = {
    UPDATE_CONTRIBUTION_DIFF: "UPDATE_CONTRIBUTION_DIFF",
    CURRENT_CALCULATION: "CURRENT_CALCULATION",
    UPDATE_NI_PAID_IN2018: "UPDATE_NI_PAID_IN2018",
    UPDATE_NI_PAID_IN2019: "UPDATE_NI_PAID_IN2019",
    UPDATE_DIFFERENCE: "UPDATE_DIFFERENCE",
    UPDATE_GROSS_INCOME:'UPDATE_GROSS_INCOME'
}